version: '3.8'
services:
  api:
    container_name: "payment-api"
    image: "nest-cloud-run"
    environment:
      - NODE_ENV=production
      - PORT=80
    build:
      context: .
      target: "production"
      dockerfile: Dockerfile
    entrypoint: ["node", "dist/main"]
    env_file:
      - .env
    ports:
      - 3000:80 # local:docker-net
